export const ROUTES = {
  Landing: 'Landing',
  Login: 'Login',
  Register: 'Register',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  PasswordResetSuccess: 'PasswordResetSuccess',
  OTPVerification: 'OTPVerification',
  OAuthSuccess: 'OAuthSuccess',
  About: 'About',
  Settings: 'Settings',
  Contact: 'Contact',
  CustomRequest: 'CustomRequest',
  CustomerHome: 'CustomerHome',
  Explore: 'Explore',
  Cart: 'Cart',
  Checkout: 'Checkout',
  Notification: 'Notification',
  Orders: 'Orders',
  CustomerTabs: 'CustomerTabs',
  CustomerStorefront: 'CustomerStorefront',
  BakeryDetail: 'BakeryDetail',
  ProductDetail: 'ProductDetail',
  CustomerProfile: 'CustomerProfile',
  OwnerHome: 'OwnerHome',
  OwnerProducts: 'OwnerProducts',
  OwnerOrders: 'OwnerOrders',
  OwnerProfile: 'OwnerProfile',
  OwnerTabs: 'OwnerTabs',
  OwnerOrderDetail: 'OwnerOrderDetail',
  PrivacyPolicy: 'PrivacyPolicy',
  TermsOfService: 'TermsOfService',
  Eula: 'Eula',
} as const;

export type RouteName = (typeof ROUTES)[keyof typeof ROUTES];
